import csv
import json
import os
import re
import sys
import time
import urllib.request
import urllib.error

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")

from pathlib import Path

# Load GitHub Token
token = None
env_candidates = [
    Path(".env"),
    Path(__file__).resolve().parent / ".env",
    Path(__file__).resolve().parents[2] / ".env"
]
for p in env_candidates:
    if p.exists():
        with open(p, "r", encoding="utf-8") as f:
            for line in f:
                if line.startswith("GITHUB_TOKEN"):
                    token = line.split("=", 1)[1].strip().strip('"').strip("'")
        if token:
            break

headers = {
    "User-Agent": "MultiModal-Validator/2.0",
    "Accept": "application/vnd.github.v3+json"
}
if token:
    headers["Authorization"] = f"token {token}"

# Strict Taxonomy Definitions:
# 1. INTERACTIVE_AI_COAUTHORED: Human author + AI pair programming assistant (Claude Code, Cursor, Copilot, Windsurf)
# 2. AUTONOMOUS_AI_AGENT: Autonomous generative agent creating code/PR (Sweep AI, Devin, ClawSweeper, OpenHands)
# 3. DETERMINISTIC_DEVOPS_BOT: Rule-based CI/package bots (Dependabot, Renovate, GitHub Actions)
# 4. PURE_HUMAN: Verified human, no AI or bot trace

INTERACTIVE_AI_TRAILERS = [
    (r"Co-authored-by:\s*(?:Claude|Cursor|Copilot|GitHub\s*Copilot|Windsurf|Codeium|Qodo)", "Git Trailer: Co-authored-by AI"),
    (r"Co-authored-by:.*<(?:noreply@anthropic\.com|cursoragent@cursor\.com|copilot@github\.com)>", "Git Trailer: AI Provider Email"),
    (r"Generated-by:\s*(?:Claude|Cursor|Copilot|Windsurf|Codeium)", "Git Trailer: Generated-by AI"),
    (r"\bAI-assisted\b(?:\s*\(Claude Code\)|\s*\(Cursor\)|\s*\(Copilot\))?", "Message Disclosure: AI-assisted"),
    (r"\bAI-generated\b", "Message Disclosure: AI-generated")
]

AUTONOMOUS_AI_SIGNATURES = [
    (r"^sweep(?:-ai)?(?:\[bot\])?$", "Autonomous AI Login: Sweep AI"),
    (r"^devin(?:-ai)?(?:-integration)?(?:\[bot\])?$", "Autonomous AI Login: Devin"),
    (r"^clawsweeper$", "Autonomous AI Login: ClawSweeper"),
    (r"steipete\+clawsweeper@gmail\.com", "Autonomous AI Email: ClawSweeper"),
    (r"Co-authored-by:.*<(?:contact@sweep\.dev|devin.*@cognition\.ai)>", "Autonomous AI Trailer"),
    (r"Co-authored-by:\s*(?:Sweep|Devin|ClawSweeper)", "Autonomous AI Trailer: Sweep/Devin")
]

DEVOPS_BOT_SIGNATURES = [
    (r"^dependabot(?:\[bot\])?$", "DevOps Bot: Dependabot"),
    (r"^renovate(?:\[bot\])?$", "DevOps Bot: Renovate"),
    (r"^github-actions(?:\[bot\])?$", "DevOps Bot: GitHub Actions"),
    (r"\[bot\]$", "Generic Bot Login [bot]"),
    (r"bot$", "Generic Bot Login suffix 'bot'")
]

# PR-Level Signals
PR_INTERACTIVE_AI_SIGNATURES = [
    (r"\[x\]\s*(?:Generated|Assisted)\s+with\s+(?:Claude|Cursor|Copilot|Windsurf|AI)", "PR Checkbox: AI Assisted/Generated"),
    (r"\[x\]\s*AI-assisted", "PR Checkbox: AI-assisted"),
    (r"(?:^|\s)ai-generated(?:$|\s)", "PR Label: ai-generated"),
    (r"(?:^|\s)claude-code(?:$|\s)", "PR Label: claude-code"),
    (r"(?:^|\s)cursor(?:$|\s)", "PR Label: cursor"),
    (r"Generated with\s+(?:Claude Code|Cursor|Copilot)", "PR Body Attribution"),
    (r"Co-authored-by:\s*(?:Claude|Cursor|Copilot)", "PR Body Co-authored-by Trailer")
]

PR_AUTONOMOUS_AI_SIGNATURES = [
    (r"(?:^|\s)sweep(?:$|\s)", "PR Label: sweep (autonomous agent)"),
    (r"^sweep(?:-ai)?(?:\[bot\])?$", "PR Author: Sweep AI"),
    (r"^devin(?:-ai)?(?:\[bot\])?$", "PR Author: Devin AI"),
    (r"This PR was generated by\s+(?:Sweep|Devin)", "PR Body: Autonomous Agent Generator")
]

PR_DEVOPS_BOT_SIGNATURES = [
    (r"^dependabot(?:\[bot\])?$", "PR Author: Dependabot"),
    (r"^renovate(?:\[bot\])?$", "PR Author: Renovate"),
    (r"(?:^|\s)dependencies(?:$|\s)", "PR Label: dependencies")
]

def fetch_json(url):
    req = urllib.request.Request(url, headers=headers)
    try:
        with urllib.request.urlopen(req) as resp:
            return json.loads(resp.read().decode("utf-8")), None
    except urllib.error.HTTPError as e:
        if e.code in (403, 429):
            time.sleep(5)
            return None, "RateLimit"
        return None, e.code
    except Exception as e:
        return None, str(e)

def get_target_repos(csv_path="Repos_Final_Sample.csv"):
    candidates = [
        Path(csv_path),
        Path(__file__).resolve().parents[2] / "02_repo_sampling" / "data" / csv_path,
        Path("02_repo_sampling/data") / csv_path,
        Path("../data") / csv_path,
    ]
    resolved_path = None
    for c in candidates:
        if c.exists():
            resolved_path = c
            break

    if not resolved_path:
        return []

    repos = []
    with open(resolved_path, "r", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for row in reader:
            url = row.get("Repo_URL", "").strip()
            name = row.get("Repo_Name", "").strip() or row.get("\ufeffRepo_Name", "").strip()
            if url:
                parts = url.rstrip("/").split("/")
                if len(parts) >= 2:
                    repos.append((name, f"{parts[-2]}/{parts[-1]}", url))
    return repos

def classify_commit(commit_obj, pr_obj=None):
    c = commit_obj.get("commit", {})
    git_author = c.get("author", {}) or {}
    message = c.get("message", "") or ""
    gh_author = commit_obj.get("author") or {}

    author_login = gh_author.get("login", "")
    author_name = git_author.get("name", "")
    author_email = git_author.get("email", "")

    # Category 1: Interactive AI Co-Authored
    interactive_clues = []
    # Category 2: Autonomous AI Agent
    autonomous_clues = []
    # Category 3: Deterministic DevOps Bot
    devops_clues = []

    # Check Git Metadata
    for pat, desc in INTERACTIVE_AI_TRAILERS:
        if re.search(pat, message, re.IGNORECASE):
            interactive_clues.append(f"Commit Trailer/Message: {desc}")
    for pat, desc in INTERACTIVE_AI_TRAILERS:
        if re.search(pat, author_name, re.IGNORECASE):
            interactive_clues.append(f"Author Name: {desc}")

    for pat, desc in AUTONOMOUS_AI_SIGNATURES:
        if author_login and re.search(pat, author_login, re.IGNORECASE):
            autonomous_clues.append(f"Actor Login: {desc}")
        if author_email and re.search(pat, author_email, re.IGNORECASE):
            autonomous_clues.append(f"Author Email: {desc}")
        if re.search(pat, message, re.IGNORECASE):
            autonomous_clues.append(f"Commit Message/Trailer: {desc}")

    for pat, desc in DEVOPS_BOT_SIGNATURES:
        if author_login and re.search(pat, author_login, re.IGNORECASE):
            devops_clues.append(f"Actor Login: {desc}")
        if author_email and re.search(pat, author_email, re.IGNORECASE):
            devops_clues.append(f"Author Email: {desc}")

    # Check PR Metadata (if linked)
    pr_clues = []
    if pr_obj:
        pr_title = pr_obj.get("title", "") or ""
        pr_body = pr_obj.get("body", "") or ""
        labels_list = [l.get("name", "") for l in pr_obj.get("labels", []) if isinstance(l, dict)]
        labels_str = " ".join(labels_list)
        pr_user = (pr_obj.get("user") or {}).get("login", "")
        pr_num = pr_obj.get("number")

        # PR Interactive signals
        for pat, desc in PR_INTERACTIVE_AI_SIGNATURES:
            if re.search(pat, pr_body, re.IGNORECASE) or re.search(pat, labels_str, re.IGNORECASE):
                pr_clues.append(f"PR #{pr_num}: {desc}")
                interactive_clues.append(f"PR #{pr_num}: {desc}")

        # PR Autonomous AI signals
        for pat, desc in PR_AUTONOMOUS_AI_SIGNATURES:
            if re.search(pat, pr_user, re.IGNORECASE) or re.search(pat, labels_str, re.IGNORECASE) or re.search(pat, pr_body, re.IGNORECASE):
                pr_clues.append(f"PR #{pr_num}: {desc}")
                autonomous_clues.append(f"PR #{pr_num}: {desc}")

        # PR DevOps Bot signals
        for pat, desc in PR_DEVOPS_BOT_SIGNATURES:
            if re.search(pat, pr_user, re.IGNORECASE) or re.search(pat, labels_str, re.IGNORECASE):
                pr_clues.append(f"PR #{pr_num}: {desc}")
                devops_clues.append(f"PR #{pr_num}: {desc}")

    # Prioritization Hierarchy
    if interactive_clues:
        return "INTERACTIVE_AI_COAUTHORED", interactive_clues, pr_clues
    elif autonomous_clues:
        return "AUTONOMOUS_AI_AGENT", autonomous_clues, pr_clues
    elif devops_clues:
        return "DETERMINISTIC_DEVOPS_BOT", devops_clues, pr_clues
    else:
        return "PURE_HUMAN", [], pr_clues

def main():
    repos = get_target_repos()
    print(f"Loaded {len(repos)} repositories.")

    max_repos = 50
    commits_per_repo = 100

    results_by_cat = {
        "INTERACTIVE_AI_COAUTHORED": [],
        "AUTONOMOUS_AI_AGENT": [],
        "DETERMINISTIC_DEVOPS_BOT": [],
        "PURE_HUMAN": []
    }

    # Tracking comparative counts: Baseline (Git-only) vs Multi-Modal (Git + PR)
    baseline_counts = {
        "INTERACTIVE_AI_COAUTHORED": 0,
        "AUTONOMOUS_AI_AGENT": 0,
        "DETERMINISTIC_DEVOPS_BOT": 0,
        "PURE_HUMAN": 0
    }
    multimodal_counts = {
        "INTERACTIVE_AI_COAUTHORED": 0,
        "AUTONOMOUS_AI_AGENT": 0,
        "DETERMINISTIC_DEVOPS_BOT": 0,
        "PURE_HUMAN": 0
    }

    uncovered_ai_examples = []
    total_commits = 0

    print("=" * 80)
    print("RUNNING REFINED 4-TIER MULTI-MODAL RE-ANALYSIS")
    print("=" * 80)

    for idx, (repo_alias, owner_repo, repo_url) in enumerate(repos[:max_repos], 1):
        print(f"[{idx}/{max_repos}] Scanning {owner_repo}...")

        commits_url = f"https://api.github.com/repos/{owner_repo}/commits?per_page={commits_per_repo}"
        commits, err = fetch_json(commits_url)
        if err or not commits:
            continue

        # Fetch recent PRs for batch matching
        prs_url = f"https://api.github.com/repos/{owner_repo}/pulls?state=all&per_page=100"
        prs, pr_err = fetch_json(prs_url)
        pr_by_num = {}
        pr_by_sha = {}
        if prs and isinstance(prs, list):
            for pr in prs:
                num = pr.get("number")
                if num: pr_by_num[str(num)] = pr
                head_sha = (pr.get("head") or {}).get("sha")
                merge_sha = pr.get("merge_commit_sha")
                if head_sha: pr_by_sha[head_sha] = pr
                if merge_sha: pr_by_sha[merge_sha] = pr

        for c in commits:
            total_commits += 1
            sha = c.get("sha", "")
            short_sha = sha[:7]
            full_commit_link = f"https://github.com/{owner_repo}/commit/{sha}"
            msg = (c.get("commit", {}).get("message", "") or "").strip()
            first_line = msg.split("\n")[0] if msg else ""
            gh_author = c.get("author") or {}
            git_author = c.get("commit", {}).get("author", {}) or {}

            # Link PR
            matched_pr = None
            if sha in pr_by_sha:
                matched_pr = pr_by_sha[sha]
            else:
                m = re.search(r"#(\d+)", msg)
                if m and m.group(1) in pr_by_num:
                    matched_pr = pr_by_num[m.group(1)]

            # 1. Baseline evaluation (NO PR)
            base_cat, base_clues, _ = classify_commit(c, pr_obj=None)
            baseline_counts[base_cat] += 1

            # 2. Multi-modal evaluation (WITH PR)
            multi_cat, multi_clues, pr_clues = classify_commit(c, pr_obj=matched_pr)
            multimodal_counts[multi_cat] += 1

            pr_number = matched_pr.get("number") if matched_pr else None
            pr_link = f"https://github.com/{owner_repo}/pull/{pr_number}" if pr_number else None

            sample_entry = {
                "repo": owner_repo,
                "short_sha": short_sha,
                "sha": sha,
                "commit_link": full_commit_link,
                "pr_number": pr_number,
                "pr_link": pr_link,
                "author_login": gh_author.get("login", "N/A"),
                "author_name": git_author.get("name", "N/A"),
                "snippet": first_line,
                "baseline_category": base_cat,
                "multimodal_category": multi_cat,
                "clues": multi_clues,
                "pr_clues": pr_clues
            }

            results_by_cat[multi_cat].append(sample_entry)

            # Did PR metadata change a HUMAN commit to AI or BOT?
            if base_cat == "PURE_HUMAN" and multi_cat in ("INTERACTIVE_AI_COAUTHORED", "AUTONOMOUS_AI_AGENT"):
                uncovered_ai_examples.append(sample_entry)

        time.sleep(0.1)

    print("\n" + "=" * 80)
    print("RE-ANALYSIS COMPLETE: REFINED TAXONOMY & METRICS")
    print("=" * 80)
    print(f"Total Commits Evaluated: {total_commits:,} across {max_repos} repositories\n")

    print("1. BASELINE (4 Git Metadata Criteria Only):")
    for k, v in baseline_counts.items():
        pct = (v / total_commits * 100) if total_commits else 0
        print(f"   - {k:30}: {v:5} ({pct:5.2f}%)")

    print("\n2. MULTI-MODAL (+ PR Metadata & Labels):")
    for k, v in multimodal_counts.items():
        pct = (v / total_commits * 100) if total_commits else 0
        print(f"   - {k:30}: {v:5} ({pct:5.2f}%)")

    ai_diff = (multimodal_counts["INTERACTIVE_AI_COAUTHORED"] + multimodal_counts["AUTONOMOUS_AI_AGENT"]) - (baseline_counts["INTERACTIVE_AI_COAUTHORED"] + baseline_counts["AUTONOMOUS_AI_AGENT"])
    print(f"\nNet AI Detection Gain (Interactive + Autonomous): +{ai_diff} commits")

    # Save complete JSON
    output_dir = Path(__file__).resolve().parent.parent / "data"
    if not output_dir.exists():
        output_dir = Path(".")
    out_file = output_dir / "refined_taxonomy_analysis.json"
    with open(out_file, "w", encoding="utf-8") as f:
        json.dump({
            "total_commits": total_commits,
            "baseline_counts": baseline_counts,
            "multimodal_counts": multimodal_counts,
            "uncovered_ai_examples": uncovered_ai_examples,
            "samples_interactive_ai": results_by_cat["INTERACTIVE_AI_COAUTHORED"][:25],
            "samples_autonomous_ai": results_by_cat["AUTONOMOUS_AI_AGENT"][:25],
            "samples_devops_bots": results_by_cat["DETERMINISTIC_DEVOPS_BOT"][:25],
            "samples_pure_human": results_by_cat["PURE_HUMAN"][:25]
        }, f, indent=2)

    print(f"Saved refined dataset to '{out_file}'")

if __name__ == "__main__":
    main()
