import csv
import json
import os
import re
import sys
import time
import urllib.request
import urllib.error

# UTF-8 encoding configuration for Windows console
if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")

from pathlib import Path

# Load .env if available
env_candidates = [
    Path(".env"),
    Path(__file__).resolve().parent / ".env",
    Path(__file__).resolve().parents[2] / ".env"
]
for p in env_candidates:
    if p.exists():
        with open(p, "r", encoding="utf-8") as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith("#") and "=" in line:
                    k, v = line.split("=", 1)
                    os.environ[k.strip()] = v.strip().strip('"').strip("'")
        break

# Heuristics Definitions

# 1. Baseline Git Metadata Criteria
INTERACTIVE_AI_LOGINS = [
    r"cursor", r"copilot", r"devin", r"claude", r"jules", r"sweep", r"codeium", r"qodo", r"clawsweeper"
]

BOT_LOGINS = [
    r"\[bot\]$", r"bot$", r"^dependabot", r"^renovate", r"^github-actions", r"^mergify"
]

INTERACTIVE_AI_EMAILS = [
    (r"noreply@anthropic\.com", "Anthropic AI Email"),
    (r"noreply@openai\.com", "OpenAI AI Email"),
    (r"copilot", "Copilot Email Keyword"),
    (r"cursor", "Cursor Email Keyword"),
    (r"devin", "Devin Email Keyword"),
    (r"sweep", "Sweep Email Keyword"),
    (r"claude", "Claude Email Keyword"),
    (r"jules", "Jules Email Keyword"),
    (r"codeium", "Codeium Email Keyword"),
    (r"qodo", "Qodo Email Keyword"),
    (r"clawsweeper", "ClawSweeper Email Keyword")
]

BOT_EMAILS = [
    (r"\[bot\]@users\.noreply\.github\.com", "GitHub Bot User Email"),
    (r"github-actions", "GitHub Actions Email"),
    (r"dependabot", "Dependabot Email"),
    (r"renovate", "Renovate Email")
]

INTERACTIVE_AI_NAMES = [
    (r"Cursor\s*Agent", "Cursor Agent Name"),
    (r"\bCursor\b", "Cursor Name"),
    (r"GitHub\s*Copilot", "GitHub Copilot Name"),
    (r"\bCopilot\b", "Copilot Name"),
    (r"\bClaude\b", "Claude AI Name"),
    (r"\bJules\b", "Jules AI Name"),
    (r"\bDevin\b", "Devin AI Name"),
    (r"\bSweep\b", "Sweep AI Name"),
    (r"ClawSweeper", "ClawSweeper Name"),
    (r"\bCodeium\b", "Codeium AI Name"),
    (r"\bQodo\b", "Qodo AI Name")
]

BOT_NAMES = [
    (r"\[bot\]", "[bot] in Name"),
    (r"\bBot\b", "Bot in Name")
]

INTERACTIVE_AI_TRAILERS = [
    (r"Co-authored-by:.*(?:cursor|copilot|claude|devin|jules|sweep|codeium|qodo)", "Co-authored-by AI Trailer"),
    (r"Generated-by:\s*(?:Cursor|Copilot|Claude|Devin|Jules|Sweep|AI)", "Generated-by AI Trailer"),
    (r"AI-generated", "AI-generated keyword in commit message"),
    (r"AI-assisted", "AI-assisted keyword in commit message"),
    (r"Assisted-by:\s*(?:Cursor|Copilot|Claude|Devin|Jules|AI)", "Assisted-by AI Trailer"),
    (r"Co-authored-by:\s*Claude", "Co-authored-by Claude"),
    (r"Co-authored-by:\s*Cursor", "Co-authored-by Cursor"),
    (r"Co-authored-by:\s*Copilot", "Co-authored-by Copilot"),
    (r"Co-authored-by:\s*Devin", "Co-authored-by Devin")
]

BOT_TRAILERS = [
    (r"Co-authored-by:.*<.*\[bot\]@users\.noreply\.github\.com>", "Co-authored-by Bot Email Trailer"),
    (r"Co-authored-by:.*\[bot\]", "Co-authored-by Bot Trailer")
]

# 2. Suggested Multi-Modal PR Signals (PR Body, Checkboxes, Labels, Templates)
PR_AI_PATTERNS = [
    (r"\[x\]\s*(?:Generated|Assisted)\s+with\s+(?:Claude|Cursor|Copilot|Devin|AI)", "PR Template Checkbox: AI Generated"),
    (r"\[x\]\s*AI-assisted", "PR Template Checkbox: AI Assisted"),
    (r"ai-generated", "PR Label: ai-generated"),
    (r"claude-code", "PR Label: claude-code"),
    (r"cursor", "PR Label: cursor"),
    (r"copilot", "PR Label: copilot"),
    (r"devin", "PR Label: devin"),
    (r"sweep", "PR Label: sweep"),
    (r"Generated by\s+(?:Claude|Cursor|Copilot|Devin|Sweep)", "PR Body Attribution"),
    (r"AI-assisted", "PR Body AI-assisted Keyword"),
    (r"Co-authored-by:.*(?:Claude|Cursor|Copilot|Devin|Sweep)", "PR Body Co-authored Trailer")
]

PR_BOT_PATTERNS = [
    (r"dependabot", "PR Label/Body Dependabot"),
    (r"renovate", "PR Label/Body Renovate"),
    (r"github-actions", "PR Label/Body GitHub Actions")
]

def evaluate_baseline(commit_data):
    git_author = commit_data.get("commit", {}).get("author", {}) or {}
    git_committer = commit_data.get("commit", {}).get("committer", {}) or {}
    message = commit_data.get("commit", {}).get("message", "") or ""
    gh_author = commit_data.get("author") or {}
    gh_committer = commit_data.get("committer") or {}

    author_login = gh_author.get("login", "")
    committer_login = gh_committer.get("login", "")
    author_name = git_author.get("name", "")
    committer_name = git_committer.get("name", "")
    author_email = git_author.get("email", "")
    committer_email = git_committer.get("email", "")

    ai_sigs = []
    bot_sigs = []

    # Logins
    for _, login in [("author_login", author_login), ("committer_login", committer_login)]:
        if not login: continue
        for pat in INTERACTIVE_AI_LOGINS:
            if re.search(pat, login, re.IGNORECASE): ai_sigs.append(f"Login AI regex '{pat}'")
        for pat in BOT_LOGINS:
            if re.search(pat, login, re.IGNORECASE): bot_sigs.append(f"Login Bot regex '{pat}'")

    # Emails
    for _, email in [("author_email", author_email), ("committer_email", committer_email)]:
        if not email: continue
        for pat, label in INTERACTIVE_AI_EMAILS:
            if re.search(pat, email, re.IGNORECASE): ai_sigs.append(label)
        for pat, label in BOT_EMAILS:
            if re.search(pat, email, re.IGNORECASE): bot_sigs.append(label)

    # Names
    for _, name in [("author_name", author_name), ("committer_name", committer_name)]:
        if not name: continue
        for pat, label in INTERACTIVE_AI_NAMES:
            if re.search(pat, name, re.IGNORECASE): ai_sigs.append(label)
        for pat, label in BOT_NAMES:
            if re.search(pat, name, re.IGNORECASE): bot_sigs.append(label)

    # Trailers
    for pat, label in INTERACTIVE_AI_TRAILERS:
        if re.search(pat, message, re.IGNORECASE): ai_sigs.append(label)
    for pat, label in BOT_TRAILERS:
        if re.search(pat, message, re.IGNORECASE): bot_sigs.append(label)

    if ai_sigs:
        return "INTERACTIVE_AI_COAUTHORED", ai_sigs
    elif bot_sigs:
        return "AUTONOMOUS_BOT", bot_sigs
    else:
        return "HUMAN_ONLY", []

def evaluate_multimodal(commit_data, linked_prs):
    base_class, base_sigs = evaluate_baseline(commit_data)
    
    pr_ai_sigs = []
    pr_bot_sigs = []

    if linked_prs:
        for pr in linked_prs:
            pr_num = pr.get("number")
            pr_title = pr.get("title", "") or ""
            pr_body = pr.get("body", "") or ""
            labels_list = [l.get("name", "") for l in pr.get("labels", []) if isinstance(l, dict)]
            pr_text = f"{pr_title}\n{pr_body}\n" + " ".join(labels_list)

            for pat, label in PR_AI_PATTERNS:
                if re.search(pat, pr_text, re.IGNORECASE):
                    pr_ai_sigs.append(f"PR #{pr_num}: {label}")
            for pat, label in PR_BOT_PATTERNS:
                if re.search(pat, pr_text, re.IGNORECASE):
                    pr_bot_sigs.append(f"PR #{pr_num}: {label}")

    if base_class == "INTERACTIVE_AI_COAUTHORED" or pr_ai_sigs:
        combined_sigs = base_sigs + pr_ai_sigs
        return "INTERACTIVE_AI_COAUTHORED", combined_sigs
    elif base_class == "AUTONOMOUS_BOT" or pr_bot_sigs:
        combined_sigs = base_sigs + pr_bot_sigs
        return "AUTONOMOUS_BOT", combined_sigs
    else:
        return "HUMAN_ONLY", []

def get_target_repos(csv_path="Repos_Final_Sample.csv"):
    candidates = [
        Path(csv_path),
        Path(__file__).resolve().parents[2] / "02_repo_sampling" / "data" / csv_path,
        Path("02_repo_sampling/data") / csv_path,
        Path("../data") / csv_path,
    ]
    resolved_path = None
    for c in candidates:
        if c.exists():
            resolved_path = c
            break

    if not resolved_path:
        return []

    repos = []
    with open(resolved_path, "r", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for row in reader:
            url = row.get("Repo_URL", "").strip()
            name = row.get("Repo_Name", "").strip() or row.get("\ufeffRepo_Name", "").strip()
            if url:
                parts = url.rstrip("/").split("/")
                if len(parts) >= 2:
                    owner_repo = f"{parts[-2]}/{parts[-1]}"
                    repos.append((name, owner_repo, url))
            elif name and "/" in name:
                repos.append((name, name, f"https://github.com/{name}"))
    return repos

def fetch_json_with_retry(url, headers, max_retries=3):
    for attempt in range(max_retries):
        req = urllib.request.Request(url, headers=headers)
        try:
            with urllib.request.urlopen(req) as resp:
                rate_limit_rem = resp.headers.get("X-RateLimit-Remaining")
                if rate_limit_rem and int(rate_limit_rem) < 20:
                    time.sleep(1)
                data = json.loads(resp.read().decode("utf-8"))
                return data, None
        except urllib.error.HTTPError as e:
            if e.code in (403, 429):
                time.sleep(4)
            elif e.code == 404:
                return None, 404
            else:
                return None, e
        except Exception:
            time.sleep(2)
    return None, "Max retries exceeded"

def main():
    token = os.environ.get("GITHUB_TOKEN") or os.environ.get("GH_TOKEN")
    headers = {
        "User-Agent": "Commit-Classification-Validator/1.0",
        "Accept": "application/vnd.github.v3+json"
    }
    if token:
        headers["Authorization"] = f"token {token}"
        print("Using GitHub Token authentication.")
    else:
        print("No GITHUB_TOKEN set. Operating unauthenticated.")

    repos = get_target_repos()
    max_repos_to_scan = 50
    commits_per_repo = 100

    total_scanned = 0
    baseline_counts = {"INTERACTIVE_AI_COAUTHORED": 0, "AUTONOMOUS_BOT": 0, "HUMAN_ONLY": 0}
    multimodal_counts = {"INTERACTIVE_AI_COAUTHORED": 0, "AUTONOMOUS_BOT": 0, "HUMAN_ONLY": 0}

    uncovered_by_pr = []
    sample_records = []

    print("=" * 80)
    print("COMPARATIVE EVALUATION: BASELINE (4 GIT CRITERIA) VS. MULTI-MODAL (+ PR SIGNALS)")
    print("=" * 80)

    for idx, (repo_alias, owner_repo, repo_url) in enumerate(repos[:max_repos_to_scan], 1):
        print(f"[{idx}/{max_repos_to_scan}] Fetching commits & PR metadata for {owner_repo}...")
        
        # 1. Fetch commits
        commits_url = f"https://api.github.com/repos/{owner_repo}/commits?per_page={commits_per_repo}"
        commits, err = fetch_json_with_retry(commits_url, headers)
        if err or not commits:
            print(f"  Skipping {owner_repo}: {err}")
            continue

        # 2. Fetch recent PRs for batch cross-referencing (1 API call per repo)
        prs_url = f"https://api.github.com/repos/{owner_repo}/pulls?state=all&per_page=100"
        prs_list, pr_err = fetch_json_with_retry(prs_url, headers)
        pr_map_by_number = {}
        pr_map_by_sha = {}
        if prs_list and isinstance(prs_list, list):
            for pr in prs_list:
                num = pr.get("number")
                if num: pr_map_by_number[str(num)] = pr
                head_sha = (pr.get("head") or {}).get("sha")
                merge_sha = pr.get("merge_commit_sha")
                if head_sha: pr_map_by_sha[head_sha] = pr
                if merge_sha: pr_map_by_sha[merge_sha] = pr

        for c in commits:
            total_scanned += 1
            sha = c.get("sha", "")
            short_sha = sha[:7]
            full_commit_link = f"https://github.com/{owner_repo}/commit/{sha}"
            commit_obj = c.get("commit", {})
            msg = (commit_obj.get("message", "") or "").strip()
            first_line = msg.split("\n")[0] if msg else ""
            git_author = commit_obj.get("author", {}) or {}
            gh_author = c.get("author") or {}

            # Find linked PRs for this commit
            linked_prs = []
            if sha in pr_map_by_sha:
                linked_prs.append(pr_map_by_sha[sha])
            
            pr_match = re.search(r"#(\d+)", msg)
            if pr_match:
                p_num = pr_match.group(1)
                if p_num in pr_map_by_number and pr_map_by_number[p_num] not in linked_prs:
                    linked_prs.append(pr_map_by_number[p_num])

            base_label, base_sigs = evaluate_baseline(c)
            multi_label, multi_sigs = evaluate_multimodal(c, linked_prs)

            baseline_counts[base_label] += 1
            multimodal_counts[multi_label] += 1

            record = {
                "repo": owner_repo,
                "sha": sha,
                "short_sha": short_sha,
                "commit_link": full_commit_link,
                "author_name": git_author.get("name", "N/A"),
                "author_login": gh_author.get("login", "N/A"),
                "snippet": first_line,
                "baseline_label": base_label,
                "multimodal_label": multi_label,
                "baseline_signatures": base_sigs,
                "multimodal_signatures": multi_sigs,
                "linked_pr_numbers": [pr.get("number") for pr in linked_prs]
            }

            # Capture commits that were missed by baseline (Human-Only) but identified as AI by Multi-Modal signals!
            if base_label == "HUMAN_ONLY" and multi_label == "INTERACTIVE_AI_COAUTHORED":
                uncovered_by_pr.append(record)

            sample_records.append(record)

        time.sleep(0.1)

    print("\n" + "=" * 80)
    print("EMPIRICAL COMPARISON RESULTS")
    print("=" * 80)
    print(f"Total Repositories Scanned                   : {min(idx, max_repos_to_scan)}")
    print(f"Total Commits Evaluated                      : {total_scanned:,}")
    print("\n1. BASELINE CLASSIFICATION (4 Git Metadata Criteria Only):")
    print(f"   - Interactive AI-Co-Authored              : {baseline_counts['INTERACTIVE_AI_COAUTHORED']:,} ({ (baseline_counts['INTERACTIVE_AI_COAUTHORED']/total_scanned*100) if total_scanned else 0:.2f}%)")
    print(f"   - Autonomous DevOps / Dependency Bots      : {baseline_counts['AUTONOMOUS_BOT']:,} ({ (baseline_counts['AUTONOMOUS_BOT']/total_scanned*100) if total_scanned else 0:.2f}%)")
    print(f"   - Pure Human-Only Commits                  : {baseline_counts['HUMAN_ONLY']:,} ({ (baseline_counts['HUMAN_ONLY']/total_scanned*100) if total_scanned else 0:.2f}%)")
    
    print("\n2. MULTI-MODAL CLASSIFICATION (4 Git Criteria + PR Metadata & Labels):")
    print(f"   - Interactive AI-Co-Authored              : {multimodal_counts['INTERACTIVE_AI_COAUTHORED']:,} ({ (multimodal_counts['INTERACTIVE_AI_COAUTHORED']/total_scanned*100) if total_scanned else 0:.2f}%)")
    print(f"   - Autonomous DevOps / Dependency Bots      : {multimodal_counts['AUTONOMOUS_BOT']:,} ({ (multimodal_counts['AUTONOMOUS_BOT']/total_scanned*100) if total_scanned else 0:.2f}%)")
    print(f"   - Pure Human-Only Commits                  : {multimodal_counts['HUMAN_ONLY']:,} ({ (multimodal_counts['HUMAN_ONLY']/total_scanned*100) if total_scanned else 0:.2f}%)")

    gain = multimodal_counts['INTERACTIVE_AI_COAUTHORED'] - baseline_counts['INTERACTIVE_AI_COAUTHORED']
    print("\n3. INCREMENTAL DETECTION GAIN:")
    print(f"   - Newly Uncovered 'Silent' AI Commits     : +{gain:,} additional commits (+{ (gain/total_scanned*100) if total_scanned else 0:.2f}% improvement in AI identification)")
    print("=" * 80)

    # Save comparative dataset
    output_dir = Path(__file__).resolve().parent.parent / "data"
    if not output_dir.exists():
        output_dir = Path(".")
    output_filepath = output_dir / "multimodal_commit_comparison.json"
    with open(output_filepath, "w", encoding="utf-8") as f:
        json.dump({
            "scanned_repos": min(idx, max_repos_to_scan),
            "total_commits": total_scanned,
            "baseline_counts": baseline_counts,
            "multimodal_counts": multimodal_counts,
            "incremental_gain_count": gain,
            "uncovered_by_pr_signals": uncovered_by_pr,
            "all_commit_samples": sample_records[:300]
        }, f, indent=2)
    print(f"\nSaved comparative dataset to '{output_filepath}'")

if __name__ == "__main__":
    main()
